### ISSUE TITLE
Rescue JSON parse failures and return raw bodies instead?

### ISSUE THREAD

**Issue by indirect** [httprb/http#126]
When making a request, if the content type returned is application/json, the body is parsed as JSON. Sadly, servers (in this case, Google's calendar API) are happy to return HTML error pages with a JSON content type.

It's impossible to even know what the error said using the HTTP library, because the request raises a JSON parsing exception rather than returning the request in a way such that the body can be printed. :(

**Comment by javierjulio** [comment]
The issue I see here is by using say a Ruby library that uses HTTP internally, I don't believe there is a way to get at the response in case of a MimeType error since the decode method just raises an `HTTP::Error` with a message but nothing else. Common case would be working with a JSON API that at exceptional times returns an HTML response (e.g. most likely due to a 5xx error). The thing is reviewing the code its just an error object with the message, no response data. Is there anyway to get the response itself from the error object?

**Comment by tarcieri** [comment]
If you really want this behavior, why not consume the body yourself and call `JSON.parse`?

I don't think it makes sense to silently downgrade to a raw body on a parse error.

**Comment by zanker** [comment]
Agreed with @tarcieri. If you're working with a server that misbehaves and returns a content type that mismatches, I think it's better to be explicit and parse it yourself then.

**Comment by javierjulio** [comment]
I wasn't suggesting a change but merely if possible to get the response in case of an error. If not, then thats ok. I'm fortunate since I'm not just the library consumer but author as well haha. The thing is my app isn't making the request, but rather through a library that is using HTTP. I realize now I should be very careful with response mime type and handle appropriately despite it being a JSON API that I'm working with. Yes the third party service I'm using does misbehave in this case. I'll be more mindful going forward. Thanks for the replies!

**Comment by ixti** [comment]
If 3rd party service misbehaves, you can write a small helper inside your library (I do that way myself. Something like this:

``` ruby
class MyCoolSomething
  class Error < StandardError; end

  def initialize
    @client = HTTP.auth(ENV["API_KEY"])
  end

  def users
    request(:get, "/users").fetch("users")
  end

  private

  def request(verb, endpoint, *args)
    res = @client.request(verb, "http://example.com#{endpoint}", *args)
    raise Error, "Request did not succeed: #{res.status}" unless res.status.ok?

    begin
       res.parse
    rescue => e
      raise Error, "Can't process response: #{e}"
    end
  ensure
    @client.close
  end
end
```

**Comment by britishtea** [comment]
What I think @javierjulio means is: is there something like a `HTTP::Error#request`?

This could be handy when dealing with 3rd party libraries (such as API wrappers) that are not properly handling errors. The better solution is of course to patch the library to properly handle errors.

**Comment by ixti** [comment]
@britishtea No, there's no such thing at the moment, and I can't see really good way to introduce it. Parse error happens not from the response actually. `#parse` is nothing more but a syntax sugar for:

``` ruby
HTTP::MimeType[response.mime_type]
  .decode(response.to_s)
```

In other words neither picking up correct mime type handler, nor decoding is actually belongs to Response in any way. At least in my opinion :D On the other hand, @httprb/core what do you guys think about adding re-raise block to `#parse`:

``` ruby
module HTTP
  class Response
    class ParseError < ResponseError
      attr_reader :response

      def initialize(response)
        @response = response
        super()
      end
    end

    def parse(...)
      # ...
    rescue
      raise ParseError, self
    end
  end
end
```
