### ISSUE TITLE
Basic GETs failing in some cases

### ISSUE THREAD

**Issue by knewter** [httprb/http#22]
I haven't tracked down anything about this yet, but I have a failing test case.

First, click this link: http://t.co/CN60RkMG

Then:

``` ruby
Http.with_follow(true).get("http://t.co/CN60RkMG")
# => ""

Http.with_follow(true).get("http://t.co/CN60RkMG").response
#=> #<HTTP/1.1 200 OK @headers={"Server"=>"nginx", "Date"=>"Fri, 01 Feb 2013 22:59:53 GMT", "Content-Type"=>"text/html; charset=UTF-8", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "Expires"=>"Fri, 01 Feb 2013 23:39:05 GMT", "X-Ua-Compatible"=>"IE=EmulateIE9,chrome=1", "Vary"=>"User-Agent,Accept-Encoding", "X-Frame-Options"=>"SAMEORIGIN", "X-Dns-Prefetch-Control"=>"on", "X-Varnish"=>"68307248 67584637", "Age"=>"1248", "Via"=>"1.1 varnish", "X-Varnish-Cache"=>"1", "X-Vserver"=>"10.90.128.188", "Cache-Control"=>"no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}>
```

Expected behaviour: The html from that page should've been returned....

**Comment by janko-m** [comment]
I was trying to use http_parser.rb on my project, and had experienced the `Could not parse data entirely` error, and I was able to reproduce it here: https://github.com/tmm1/http_parser.rb/issues/29#issuecomment-309976363. Basically it happens when the first string with HTTP headers includes some binary body.

This apparently isn't a problem anymore in HTTP.rb, but I'm just trying to understand what was the fix/workaround for it. In my project I won't be able to use http_parser.rb because of that bug.
