### ISSUE TITLE
Frequent HTTP::ConnectionError with persistent connection

### ISSUE THREAD

**Issue by britishtea** [httprb/http#420]
We recently switched to using persistent connections and started seeing requests fail frequently due to a `HTTP::ConnectionError`, specifically the one raised here in [`HTTP::Connection#read_headers!`](https://github.com/httprb/http/blob/master/lib/http/connection.rb#L100).

I suspect these are raised because the destination server has closed the connection before `HTTP::Connection` thinks the Keep-Alive timeout expired (`@conn_expires_at`). A quick `lsof` showed quite a few TCP sockets in the `CLOSE_WAIT` state, meaning the destination server closed the connection but we didn't (yet).

If I'm correct, would it be interesting to simply reconnect and retry (just once) when this happens? I think this situation too common to be called an `Exception` ;)

**Comment by tarcieri** [comment]
At that point in the request lifecycle the connection is not idle: it has just sent a request and is awaiting a response.

For it to get into this state means something weird is happening. It could be it has managed to send a TCP packet (small requests should fit in a single one since we're Nagle friendly) and then shortly thereafter receives a RST or NACK. So these errors would, at the very least, indicate a bit of a race between the client and server side timeouts, if that's actually what's happening.

Rather than implementing a swallow-and-retry mechanism based on a hunch (which might not be a bad idea), how about you test your hypothesis by adjusting the local timeouts to ensure the client will (almost) always time out shortly before the server?

**Comment by zanker** [comment]
Because of how all the various buffers and low level failures in networking work, we can't really do that. It's possible to have a request that succeeds on the server, but fails on the client when trying to read the headers. 

If you're seeing timeout errors, it likely means something (like a load balancer) between the client and server has mismatched Keep-Alive settings. It's a bit of black magic to make keep alive work sanely.

**Comment by tarcieri** [comment]
Yeah, so I'm going to close this because one way or another this is an error: a request was sent, then the socket was closed.

If you think an automatic retry mechanism is the best solution for your problem, please open an issue with a more detailed proposal of exactly what you want.
