### ISSUE TITLE
Incompatibility with JRuby v9.2.0.0 due to problem with http_parser.rb v0.6.0.

### ISSUE THREAD

**Issue by clonezone** [httprb/http#475]
See [http_parser.rb bug report](https://github.com/tmm1/http_parser.rb/issues/58).

**Comment by ixti** [comment]
We have plans on switching http parser. If I will have some time this weekned - will try to work on that.

**Comment by jrochkind** [comment]
Def interested in this working with jruby 9.2 asap, following.

**Comment by ixti** [comment]
I have cut 5.0.0 pre release version of gem with switch to updated http parser. This should be fixed now.

**Comment by jrochkind** [comment]
Oh nice!  Thanks!

Are there release notes or a URL to a relevant PR or commit about the changed http parser?  I'm curious about the details, if what's used in MRI and Jruby both changed, to the same thing, what it is, etc.; 

since previous http parser (at least in jruby?) was a third-party thing that ended up unmaintained, interested in looking at social context of the new parser and it's maintainance story.

**Comment by ixti** [comment]
This is the commit: https://github.com/httprb/http/commit/f1db84f38601960f94ce7defa3a546967b292f00

Right now we switched to maintained ffi-based http parser: https://github.com/cotag/http-parser
But in future I plan on getting rid of 3rd party dependency and have our own ffi bindings to joyent's http parser (mostly because I don't like `http-parser`'s (gem) API).

**Comment by jrochkind** [comment]
Thanks! So nice to see http.rb getting maintenance!
