### ISSUE TITLE
Non capitalized HTTP headers

### ISSUE THREAD

**Issue by ninoseki** [httprb/http#524]
Sorry for a dumb question.

I have to work with an API server which deals HTTP headers in case-sensitive manner.
(Yep I know that is a RFC violation)

Is there a good way to send non-capitalized HTTP headers?

**Comment by tarcieri** [comment]
@ixti neat! SGTM 👍

**Comment by brasic** [comment]
Hi!  Just came across this issue while checking to see if anyone had run into the problem we are currently dealing with.  An API we need to communicate with requires a particular header be specified with an underscore in the header name.  It's otherwise case-insensitive.  HTTP.rb makes it impossible to pass a header in an underscore because of this line, which transforms it to `-`: https://github.com/httprb/http/blob/e31d0a534cd39726ca363e1ab2e9d8e314d61581/lib/http/headers.rb#L206

I would argue that the behavior of `HTTP::Headers#normalize_header` violates [RFC 7230](http://tools.ietf.org/html/rfc7230#section-3.2), which allows the `_` character to be part of a header name.  We can monkeypatch this for now on our side but are there any thoughts on making the canonicalization algorithm spec-compliant?  I don't know of any case-sensitivity scheme that considers `_` and `-` to be equivalent.  I'd be happy to open a PR to remove `_` from the split regex but that would likely require a major version bump (looking at the specs, lots of code depends on `_` canonicalizing as `-`).

**Comment by ixti** [comment]
@brasic yes - I'm working on refactoring HTTP::Headers completely so that it will llow to pass any RFC compliant header (with or without normalization).

**Comment by Hendrione-Moka** [comment]
any update for this? I still got the issue.

**Comment by ixti** [comment]
I had no time to work on this yet.

**Comment by joshuaflanagan** [comment]
Just ran into this again, dealing with an API that has case-sensitive headers. That may be "wrong" on their side, but it is what it is, and switching http libraries is much easier than getting an external API to  change their behavior.
Do you have an in-process branch? I'd be happy to take a stab at fleshing it out. Would rather do that than switch libraries.

**Comment by tarcieri** [comment]
@joshuaflanagan I think if you implemented the change @ixti suggested here it'd be accepted, and shouldn't be too difficult: https://github.com/httprb/http/issues/524#issuecomment-460014322
