### ISSUE TITLE
Time to drop http-parser?

### ISSUE THREAD

**Issue by utkarsh2102** [httprb/http#604]
Hi,

https://github.com/httprb/http/blob/8b432a79072235ec445ecc3e2763b6efca64490b/http.gemspec#L33

Can we patch http to not use http-parser because it looks like it is not being maintained actively; last commit was in October 2018.
Or is there any alternative that we could possibly use?

**Comment by ixti** [comment]
We had plans of switching to own ffi binding, but we don't have enough bandwidth to do so. Meanwhile, you should not worry about http-parser as long as it works fine.

**Comment by Jcambass** [comment]
We run into random segfaults when we upgraded from `4.1.1` to `4.4.1`. After some digging we found that this was [caused by the new Compacting GC in ruby 2.7 and the `ffi` library ](https://github.com/ffi/ffi/issues/742)used by `http-parser`. `ffi` has [already issued a fix](https://github.com/ffi/ffi/commit/6662bccd0bff2f64b79380e23850548af76637b7) for this.

For now we fixed this by manually including `ffi 1.13.1` in our gemfile to include the fix. I also [opened a PR](https://github.com/cotag/http-parser/pull/7) to require at least ffi 1.13.1. 

However, this still makes me wonder if this project should either bring it's own ffi binding (if there are resources) or maybe more realistic, try to take over (if really needed, fork) `http-parser`.
