### ISSUE TITLE
Make HTTP::Feature work like rack middleware 

### ISSUE THREAD

**Issue by souk4711** [httprb/http#767]
I am working on [http-session](https://github.com/souk4711/http-session) (almost done) to support cookies and caching. I found that the HTTP::Feature does not work like the Rack middleware, e.g. executing orders:

```ruby
require "http"

cls = Class.new(HTTP::Feature) do
  @orders = []

  def self.orders
    @orders
  end

  def initialize(id:)
    @id = id
  end

  def wrap_request(req)
    self.class.orders << "req.#{@id}"
    req
  end

  def wrap_response(res)
    self.class.orders << "res.#{@id}"
    res
  end

  HTTP::Options.register_feature(:feature_orders_1, self)
  HTTP::Options.register_feature(:feature_orders_2, self)
end

sub = HTTP.use(
  feature_orders_1: {id: 1},
  feature_orders_2: {id: 2}
)
sub.get("https://httpbin.org/cache/0") 


# Expect: ["req.1", "req.2", "res.2", "res.1"]
# Actual: ["req.1", "req.2", "res.1", "res.2"]
p cls.orders
```

The [PR#766](https://github.com/httprb/http/pull/766) attempts to address this and make HTTP::Feature work more like Rack middleware, so that developers can more easily implement their own features, like auth, retry, cache, etc.

**Note that this PR may break some existing code that depends on orders, and [replay function in webmock](https://github.com/bblimke/webmock/blob/63940ac95345968cf435820a62102d913441862c/lib/webmock/http_lib_adapters/http_rb/webmock.rb#L46).**

**Comment by ixti** [comment]
Oh. I really like that you've started working on session gem. I was thinking about it for a very long time (and due to some personal issues never had time for that). I was thinkign about a bit different API for that though:

``` ruby
session = HTTP::Session.new(...)

session.with do |http|
  http.headers(...).get(...)
end
```

The idea I had was to use connection pool, so that connection would be kept alive just like in browsers.

**Comment by ixti** [comment]
On the features order of execution — I think we should provide them with the expected order of the execution. In rack middlewares world, you can tell where to inject the middleware. We should come with similar solution, so that features will be executed in predictable order.

``` ruby
HTTP.use(:feature_1).use(:feature_2, before: :feature_1)
```

Or using "weights" on features themselves (this will be less predicatble though):

```
class AutoInflateFeature < Feature
  weight 9000

  ...

end


class LoggingFeature < Feature
  weight 0
end
```

**Comment by tarcieri** [comment]
However that ordering is determined, I think reversing that ordering for processing responses as in #766 better maps to the sort of LIFO/FILO ordering you'd get with middlewares, where the ordering for middlewares lives in the call stack

**Comment by ixti** [comment]
> However that ordering is determined, I think reversing that ordering for processing responses as in #766 better maps to the sort of LIFO/FILO ordering you'd get with middlewares, where the ordering for middlewares lives in the call stack

I totally agree with that.
